# Generated by Django 5.0.6 on 2024-08-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projec',
            new_name='Project',
        ),
    ]
